// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLOtK-Nm-aq0xmZl_5Sym7z0GXrCFj0N4',
    appId: '1:144814382756:android:845c2474d21a1440879031',
    messagingSenderId: '144814382756',
    projectId: 'uber-clone-e445f',
    databaseURL: 'https://uber-clone-e445f-default-rtdb.firebaseio.com',
    storageBucket: 'uber-clone-e445f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXWrpPFsj4ovFpoBWuoaf8nZ7zGeTKOZw',
    appId: '1:144814382756:ios:c679eaa298c0c302879031',
    messagingSenderId: '144814382756',
    projectId: 'uber-clone-e445f',
    databaseURL: 'https://uber-clone-e445f-default-rtdb.firebaseio.com',
    storageBucket: 'uber-clone-e445f.appspot.com',
    iosClientId: '144814382756-evsc4fhkgi21mk4kklejbf9dnq2bj1ru.apps.googleusercontent.com',
    iosBundleId: 'com.muhammadali.riderApp',
  );
}
